"""Initial schema migration

Revision ID: a7a92ad2126a
Revises: 
Create Date: 2026-09-17 00:48:43.724609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a92ad2126a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from services.database.session import Base
import services.database.models  # ensure models are registered


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    Base.metadata.create_all(bind)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('agent_type',
               existing_type=sa.Enum('CONCIERGE', 'BOOKING', 'AVAILABILITY', 'SUPPORT', 'ACTIVITIES', 'RESTAURANT', 'VOICE', 'HOSTEL_AI_AGENT', name='agenttype'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
